baseURL = "https://nchealthworkforce.unc.edu"
languageCode = "en-us"
title = "NC Health Workforce"


[outputs]
  home = ["HTML", "RSS", "JSON"] 

  [params]
  searchSections = ["blog", "reports", "interactive"]

  [markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

