baseURL = "https://romantic-bhaskara-545295.netlify.app/"
languageCode = "en-us"
title = "NC Health Workforce"


[outputs]
  home = ["HTML", "RSS", "JSON"] 

  [params]
  searchSections = ["blog", "brief"]
